### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ZdenekM** [typilus/typilus-action#10]
```
Diff GET Status Code:  200
Traceback (most recent call last):
  File "/usr/src/entrypoint.py", line 81, in <module>
    changed_files = get_changed_files(diff_rq.text)
  File "/usr/src/changeutils.py", line 38, in get_changed_files
    assert file_diff_lines[3].startswith("---")
IndexError: list index out of range
```
[logs_302.zip](https://github.com/typilus/typilus-action/files/5372588/logs_302.zip)

**Comment by bzz** [comment]
@ZdenekM #9 fixes this issue
